/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pbfwkycxnmxflqngztvi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZndreWN4bm14Zmxxbmd6dHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMjE4MTksImV4cCI6MjA3ODc5NzgxOX0.L0ITkNa3-EZkb0-TIU1U4ONfYCk6vVftNNZY761WuDk"